### ISSUE TITLE
Default value for CSS class

### ISSUE THREAD

**Issue by cmartin6** [oveleon/contao-component-style-manager#45] opened 2021-04-08 07:18 UTC
It would be nice to have the possibility to set a default value for a specific group. For example "gridColumns - Columns" -> Default value 12 Columns...

**Comment by doishub** [comment] 2021-04-08 10:41
So you want to have a default value always be used when no value is selected? Wouldn't this also be reached if the blank option could be set per CSS category? This would allow multiple default options to be defined for a component. The component itself would have to be saved in any case.

(Duplicate of #29)

**Offtopic**: 
Which grid framework do you use? For example, in our [framework](https://github.com/contao-thememanager/core) grid elements without "col-*" are automatically defined as "col-12".

**Comment by cmartin6** [comment] 2021-04-08 10:45
I am using the bootstrap grid framework. Exaclty, i want to have a default value if no css is selected in the select-menu. Of course, a blank option with a default value would provide the desired feature.

**Comment by doishub** [comment] 2021-04-08 11:14
Ok. I think this is the best way and should be implementable quickly.

**Comment by doishub** [comment] 2021-04-14 12:55
Added  in `2.5.0`

**Closed by doishub** 2021-04-14 12:55 UTC
Labels: enhancement
